{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?id_string ?is_active ?whom ?purpose ?expires_date ?uuid
                (?link AS ?uri) (?rest AS ?originating_blank_node)
                ?order_index
WHERE {
  GRAPH <{{state_graph}}> {
    ?item_uri          shst:private_links/rdf:rest* ?rest .
    ?rest              rdf:first                ?link ;
                       shst:index               ?order_index .
    ?item_uri          shst:container           ?container .
    ?container         rdf:type/rdfs:subClassOf shst:Container .
    ?link              rdf:type                 shst:PrivateLink .
    OPTIONAL { ?link   shst:is_active            ?is_active . }
    OPTIONAL { ?link   shst:whom                 ?whom . }
    OPTIONAL { ?link   shst:purpose              ?purpose . }
    OPTIONAL { ?link   shst:expires_date         ?expires_date . }
    {%- if account_uuid is not none %}
    ?container         shst:account              <account:{{account_uuid}}> .
    {%- endif %}
  }
  {%- if id_string is not none %}
  ?link                shst:id                   {{id_string | safe}} .
  BIND({{id_string | safe}} AS ?id_string)
  {% else %}
  ?link                shst:id                   ?id_string .
  {%- endif %}
  {%- if item_uri is not none %}
  FILTER(?item_uri = <{{item_uri}}>)
  {%- endif %}

  BIND(STRAFTER(STR(?link), "private_link:") AS ?uuid)
}
{% endblock %}
