{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?file ?bytes
{%- if extended_properties is defined and extended_properties %}
                ?name ?filesystem_location ?is_link_only ?id ?is_public
                ?supplied_md5 ?computed_md5 ?uuid ?container_uuid
{%- endif %}
WHERE {
  GRAPH <{{state_graph}}> {
    ?dataset        rdf:type            shst:Dataset .
    {%- if published_only %}
    ?dataset        shst:published_date ?published_date .
    {%- endif %}
    ?dataset        shst:files/rdf:rest*/rdf:first ?file .
    ?file           rdf:type            shst:File .
    ?file           shst:size           ?bytes .
{%- if extended_properties is defined and extended_properties %}
    ?dataset        shst:container      ?container .
    OPTIONAL { ?dataset shst:is_public  ?is_public . }
    OPTIONAL { ?file  shst:id           ?id . }
    OPTIONAL { ?file  shst:name         ?name . }
    OPTIONAL { ?file  shst:filesystem_location ?filesystem_location . }
    OPTIONAL { ?file  shst:is_link_only ?is_link_only . }
    OPTIONAL { ?file  shst:supplied_md5 ?supplied_md5 . }
    OPTIONAL { ?file  shst:computed_md5 ?computed_md5 . }
    BIND (STRAFTER(STR(?file), "file:") AS ?uuid)
    BIND (STRAFTER(STR(?container), "container:") AS ?container_uuid)
{%- endif %}
  }
{%- if filters is not none %}{{ filters | safe }}{% endif %}
}
{% endblock %}
