{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    {%- if name is not none: %}
    ?session shst:editable   ?editable .
    ?session shst:name       ?name .
    {%- endif %}{% if active is not none: %}
    ?session shst:active     ?active .
    {%- endif %}
  }
}
INSERT {
  GRAPH <{{state_graph}}> {
    {%- if name is not none: %}
    ?session shst:name       {{name | safe}} .
    {%- endif %}{% if active is not none: %}
    ?session shst:active     {{active | safe}} .
    {%- endif %}
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?session  rdf:type                   shst:Session .
    ?session  shst:account               ?account .
    {%- if name is not none: %}
    ?session  shst:name                  ?name .
    ?session  shst:editable              1 .
    {%- endif %}
    ?session  shst:active                ?active .
  }
  FILTER (?account = <account:{{account_uuid}}>)
  FILTER (?session = <session:{{session_uuid}}>)
}
{% endblock %}
