{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    {%- if name is not none %}
    ?project          shst:name                  ?name .
    {%- endif %}{% if namespace is not none %}
    ?project          shst:namespace             ?namespace .
    {%- endif %}
  }
}
INSERT {
  GRAPH <{{state_graph}}> {
    {%- if name is not none %}
    ?project          shst:name                  {{name | safe}} .
    {%- endif %}{% if namespace is not none %}
    ?project          shst:namespace             {{namespace | safe}} .
    {%- endif %}
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?project              rdf:type                  shst:Project .
    ?project              shst:created_by           <account:{{account_uuid}}> .
    OPTIONAL { ?project   shst:name                 ?name . }
    OPTIONAL { ?project   shst:namespace            ?namespace . }
  }
  FILTER (?project = <project:{{uuid}}>)
}
{% endblock %}
