{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    {%- if is_active is not none %}
    ?account          shst:is_active             ?is_active .
    {%- endif%}{% if email is not none %}
    ?account          shst:email                 ?email .
    {%- endif%}{% if job_title is not none %}
    ?account          shst:job_title             ?job_title .
    {%- endif%}{% if first_name is not none %}
    ?account          shst:first_name            ?first_name .
    ?author           shst:first_name            ?author_first_name .
    {%- endif%}{% if last_name is not none %}
    ?account          shst:last_name             ?last_name .
    ?author           shst:last_name             ?author_last_name .
    {%- endif%}{% if full_name is not none %}
    ?author           shst:full_name             ?author_full_name .
    {%- endif%}{% if location is not none %}
    ?account          shst:location              ?location .
    {%- endif%}{% if twitter is not none %}
    ?account          shst:twitter               ?twitter .
    {%- endif%}{% if linkedin is not none %}
    ?account          shst:linkedin              ?linkedin .
    {%- endif%}{% if website is not none %}
    ?account          shst:website               ?website .
    {%- endif%}{% if biography is not none %}
    ?account          shst:biography             ?biography .
    {%- endif%}{% if institution_user_id is not none %}
    ?account          shst:institution_user_id   ?institution_user_id .
    {%- endif%}{% if institution_id is not none %}
    ?account          shst:institution_id        ?institution_id .
    {%- endif%}{% if domain is not none %}
    ?account          shst:domain                ?domain .
    {%- endif%}{% if profile_image is not none %}
    ?account          shst:profile_image         ?profile_image .
    {%- endif%}{% if maximum_file_size is not none %}
    ?account          shst:maximum_file_size     ?maximum_file_size .
    {%- endif%}{% if modified_date is not none %}
    ?account          shst:modified_date         ?modified_date .
    {%- endif%}
  }
}
INSERT {
  GRAPH <{{state_graph}}> {
    {%- if is_active is not none %}
    ?account          shst:is_active           {{is_active}} .
    {%- endif%}{% if email is not none %}
    ?account          shst:email               {{email | safe}} .
    {%- endif%}{% if job_title is not none %}
    ?account          shst:job_title           {{job_title | safe}} .
    {%- endif%}{% if first_name is not none %}
    ?account          shst:first_name          {{first_name | safe}} .
    ?author           shst:first_name          {{first_name | safe}} .
    {%- endif%}{% if last_name is not none %}
    ?account          shst:last_name           {{last_name | safe}} .
    ?author           shst:last_name           {{last_name | safe}} .
    {%- endif%}{% if full_name is not none %}
    ?author           shst:full_name           {{full_name | safe}} .
    {%- endif%}{% if location is not none %}
    ?account          shst:location            {{location | safe}} .
    {%- endif%}{% if twitter is not none %}
    ?account          shst:twitter             {{twitter | safe}} .
    {%- endif%}{% if linkedin is not none %}
    ?account          shst:linkedin            {{linkedin | safe}} .
    {%- endif%}{% if website is not none %}
    ?account          shst:website             {{website | safe}} .
    {%- endif%}{% if biography is not none %}
    ?account          shst:biography           {{biography | safe}} .
    {%- endif%}{% if institution_user_id is not none %}
    ?account          shst:institution_user_id {{institution_user_id}} .
    {%- endif%}{% if institution_id is not none %}
    ?account          shst:institution_id      {{institution_id}} .
    {%- endif%}{% if domain is not none %}
    ?account          shst:domain              {{domain | safe}} .
    {%- endif%}{% if profile_image is not none %}
    ?account          shst:profile_image       <{{profile_image | safe}}> .
    {%- endif%}{% if maximum_file_size is not none %}
    ?account          shst:maximum_file_size   {{maximum_file_size}} .
    {%- endif%}{% if modified_date is not none %}
    ?account          shst:modified_date       {{modified_date | safe}} .
    {%- endif%}
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?account              rdf:type                  shst:Account .

    OPTIONAL { ?account   shst:is_active             ?is_active . }
    OPTIONAL { ?account   shst:email                 ?email . }
    OPTIONAL { ?account   shst:job_title             ?job_title . }
    OPTIONAL { ?account   shst:first_name            ?first_name . }
    OPTIONAL { ?account   shst:last_name             ?last_name . }
    OPTIONAL { ?account   shst:location              ?location . }
    OPTIONAL { ?account   shst:twitter               ?twitter . }
    OPTIONAL { ?account   shst:linkedin              ?linkedin . }
    OPTIONAL { ?account   shst:website               ?website . }
    OPTIONAL { ?account   shst:biography             ?biography . }
    OPTIONAL { ?account   shst:institution_user_id   ?institution_user_id . }
    OPTIONAL { ?account   shst:institution_id        ?institution_id . }
    OPTIONAL { ?account   shst:domain                ?domain . }
    OPTIONAL { ?account   shst:profile_image         ?profile_image . }
    OPTIONAL { ?account   shst:maximum_file_size     ?maximum_file_size . }
    OPTIONAL { ?account   shst:modified_date         ?modified_date . }

    OPTIONAL {
      ?author            rdf:type                   shst:Author ;
                         shst:account               ?account .
      OPTIONAL { ?author shst:first_name            ?author_first_name . }
      OPTIONAL { ?author shst:last_name             ?author_last_name . }
      OPTIONAL { ?author shst:full_name             ?author_full_name . }
    }

  }
  FILTER (?account = <account:{{account_uuid}}>)
}
{% endblock %}
