{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    {%- if is_active is not none %}
    ?link     shst:is_active        ?is_active .
    {%- endif %}{% if expires_date is not none %}
    ?link     shst:expires_date     ?expires_date .
    {%- endif %}{% if read_only is not none %}
    ?link     shst:read_only        ?read_only .
    {%- endif %}
  }
}
INSERT {
  GRAPH <{{state_graph}}> {
    {%- if is_active is not none %}
    ?link     shst:is_active        {{is_active}} .
    {%- endif %}{% if expires_date is not none %}
    ?link     shst:expires_date     {{expires_date | safe}} .
    {%- endif %}{% if read_only is not none %}
    ?link     shst:read_only        {{read_only}} .
    {%- endif %}
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?container       rdf:type/rdfs:subClassOf shst:Container ;
                     shst:account              ?account ;
                     ?container_predicate      ?item_uri .

    ?item_uri        shst:private_links/rdf:rest*/rdf:first ?link .

    ?link            rdf:type             shst:PrivateLink ;
                     shst:id               ?id_string .

    OPTIONAL { ?link shst:is_active        ?is_active . }
    OPTIONAL { ?link shst:expires_date     ?expires_date . }
    OPTIONAL { ?link shst:read_only        ?read_only . }
  }
  FILTER (?container_predicate = shst:draft || ?container_predicate = shst:latest_published_version)
  FILTER (?item_uri   = <{{item_uri}}>)
  FILTER (?account    = <account:{{account_uuid}}>)
  {%- if id_string is not none %}
  FILTER (?id_string  = {{id_string | safe}})
  {%- endif %}
}
{% endblock %}
