{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    {%- if title is not none %}
    ?collection           shst:title                ?title .
    {%- endif%}{% if description is not none %}
    ?collection           shst:description          ?description .
    {%- endif%}{% if doi is not none %}
    ?collection           shst:doi                  ?doi .
    {%- endif%}{% if resource_doi is not none %}
    ?collection           shst:resource_doi         ?resource_doi .
    {%- endif%}{% if resource_title is not none %}
    ?collection           shst:resource_title       ?resource_title .
    {%- endif%}{% if group_id is not none %}
    ?collection           shst:group_id             ?group_id .
    {%- endif%}{% if time_coverage is not none %}
    ?collection           shst:time_coverage        ?time_coverage .
    {%- endif%}{% if publisher is not none %}
    ?collection           shst:publisher            ?publisher .
    {%- endif%}{% if language is not none %}
    ?collection           shst:language             ?language .
    {%- endif%}{% if contributors is not none %}
    ?collection           shst:contributors         ?contributors .
    {%- endif%}{% if geolocation is not none %}
    ?collection           shst:geolocation          ?geolocation .
    {%- endif%}{% if longitude is not none %}
    ?collection           shst:longitude            ?longitude .
    {%- endif%}{% if latitude is not none %}
    ?collection           shst:latitude             ?latitude .
    {%- endif%}{% if organizations is not none %}
    ?collection           shst:organizations        ?organizations .
    {%- endif%}{% if container_doi is not none %}
    ?container            shst:doi                  ?container_doi .
    {%- endif%}{% if first_online_date is not none %}
    ?container            shst:first_online_date    ?first_online_date .
    {%- endif%}
    ?collection           shst:modified_date        ?modified_date .
  }
}
INSERT {
  GRAPH <{{state_graph}}> {
    {%- if title is not none %}
    ?collection           shst:title                {{title | safe}} .
    {%- endif%}{% if description is not none %}
    ?collection           shst:description          {{description | safe}} .
    {%- endif%}{% if doi is not none %}
    ?collection           shst:doi                  {{doi | safe}} .
    {%- endif%}{% if resource_doi is not none %}
    ?collection           shst:resource_doi         {{resource_doi | safe}} .
    {%- endif%}{% if resource_title is not none %}
    ?collection           shst:resource_title       {{resource_title | safe}} .
    {%- endif%}{% if group_id is not none %}
    ?collection           shst:group_id             {{group_id}} .
    {%- endif%}{% if time_coverage is not none %}
    ?collection           shst:time_coverage        {{time_coverage | safe}} .
    {%- endif%}{% if publisher is not none %}
    ?collection           shst:publisher            {{publisher | safe}} .
    {%- endif%}{% if language is not none %}
    ?collection           shst:language             {{language | safe}} .
    {%- endif%}{% if contributors is not none %}
    ?collection           shst:contributors         {{contributors | safe}} .
    {%- endif%}{% if geolocation is not none %}
    ?collection           shst:geolocation          {{geolocation | safe}} .
    {%- endif%}{% if longitude is not none %}
    ?collection           shst:longitude            {{longitude | safe}} .
    {%- endif%}{% if latitude is not none %}
    ?collection           shst:latitude             {{latitude | safe}} .
    {%- endif%}{% if organizations is not none %}
    ?collection           shst:organizations        {{organizations | safe}} .
    {%- endif%}{% if container_doi is not none %}
    ?container            shst:doi                  {{container_doi | safe}} .
    {%- endif%}{% if first_online_date is not none %}
    ?container            shst:first_online_date    {{first_online_date | safe}} .
    {%- endif%}
    ?collection           shst:modified_date        {{modified_date | safe}} .
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?container          rdf:type                 shst:CollectionContainer .
    ?container          shst:account              ?account .
    ?container          shst:draft                ?collection .

    ?collection         rdf:type                 shst:Collection .

    OPTIONAL { ?collection shst:title                ?title . }
    OPTIONAL { ?collection shst:description          ?description . }
    OPTIONAL { ?collection shst:doi                  ?doi . }
    OPTIONAL { ?collection shst:group_id             ?group_id . }
    OPTIONAL { ?collection shst:resource_doi         ?resource_doi . }
    OPTIONAL { ?collection shst:resource_title       ?resource_title . }
    OPTIONAL { ?collection shst:modified_date        ?modified_date . }
    OPTIONAL { ?collection shst:publisher            ?publisher . }
    OPTIONAL { ?collection shst:language             ?language . }
    OPTIONAL { ?collection shst:time_coverage        ?time_coverage . }
    OPTIONAL { ?collection shst:geolocation          ?geolocation . }
    OPTIONAL { ?collection shst:longitude            ?longitude . }
    OPTIONAL { ?collection shst:latitude             ?latitude . }
    OPTIONAL { ?collection shst:organizations        ?organizations . }
    OPTIONAL { ?collection shst:contributors         ?contributors . }
    OPTIONAL { ?container  shst:doi                  ?container_doi . }
    OPTIONAL { ?container  shst:first_online_date    ?first_online_date . }
  }
{%- if account_uuid is not none: %}
  FILTER (?account = <account:{{account_uuid}}>)
{%- endif %}
  FILTER (?collection = <{{collection_uri | safe}}>)
}
{% endblock %}
