{{- if index .Values "cert-manager" "enabled" }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-issuer
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,post-delete
    "helm.sh/hook-weight": "1"
spec:
  acme:
    email: {{ .Values.contactEmail }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-secrets
    solvers:
    - http01:
        ingress:
          class: public
{{- range .Values.hostnames }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .host }}-certificate
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,post-delete
    "helm.sh/hook-weight": "1"
spec:
  secretName: {{ .host }}-https-cert
  duration: 2160h # 90d
  renewBefore: 720h # 30d
  isCA: false
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    encoding: PKCS1
    size: 256
  encodeUsagesInRequest: false
  usages:
    - server auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - {{ .host }}
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-issuer
    kind: Issuer
{{- end }}
{{- end }}
