{{- range .Values.persistentVolumes }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .storageClass }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .name }}-pv
spec:
  capacity:
    storage: {{ .size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .storageClass }}
  hostPath:
    path: {{ .hostPath }}
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
spec:
  storageClassName: {{ .storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size }}
{{- end }}
